### ISSUE TITLE
How to Create a Dynamic Search Box Attached with the Same Object

### ISSUE THREAD

**Issue by riazsfclouds** [ramanathansj/salesforce-lightning-datatable#1]
I was trying to create a Seach panel at top of the Page to search the Records 
Can you please help on this

**Comment by ramanathansj** [comment]
you have two options to do it,

1. Simple option is to add a text box with search button to data table component and append search string as where clause filter to {!v.whereclause}  (test your SOQL in workbench before making this change) and call helper.queryRows in controller to re-render datatable

2. Complex one If you want to make search box as a separate component, you need to create an event and include it datatable component for it to listen and fire your helper.queryrows again. (same as #1). refer event handling in documentation for help.

**Comment by riazsfclouds** [comment]
Hi Ramanathan ,

Thanks for the reply
i will try it out
and really it was an amazing blog.

Regards,
Riaz

**Comment by ramanathansj** [comment]
Thanks for the feedback and glad to hear its useful.
